version: 2.0
jobs:
  build:
    working_directory: ~/subtend
    docker:
      - image: fpco/stack-build:latest

    steps:
      - checkout

      ##### Building library
      - restore_cache:
          keys: 
            - dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "subtend.cabal" }}
            - dot-stack-{{ checksum "stack.yaml" }}-build
            - dot-stack-{{ checksum "stack.yaml" }}-setup

      - restore_cache:
          key: dot-stack-work-{{ checksum "stack.yaml" }}

      - run:
          name: Stack setup
          command: stack setup

      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}-setup
          paths:
            - ~/.stack

      - run:
          name: Compiling
          command: stack build --test --no-run-tests 

      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "subtend.cabal" }}
          paths:
            - ~/.stack
      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}-build
          paths:
            - ~/.stack

      - save_cache:
          key: dot-stack-work-{{ checksum "stack.yaml" }}
          paths: ~/subtend/.stack-work

      ##### Running tests
      - run:
          name: Running tests
          command: stack test
